practicescribe-elasticsearch:
  container_name: practicescribe-elasticsearch
  image: elasticsearch:1.7.3
  # volumes:
  #   - ~/volumes/jhipster/PracticeScribe/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
practicescribe-postgresql:
  container_name: practicescribe-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/PracticeScribe/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=PracticeScribe
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
